## Panjabi-gpt

In [2]:
from pathlib import Path
import re
import json
import math
from collections import Counter

import pandas as pd

## path

In [3]:
project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data_dir = project_root / "data"
outputs_dir = project_root / "outputs"

outputs_dir.mkdir(parents=True, exist_ok=True)

print("Project root:", project_root)
print("Data dir:", data_dir)
print("Outputs dir:", outputs_dir)

Project root: /Users/gurpejsingh/Desktop/gpt2-finetune-mac/training-punjabi-gpt
Data dir: /Users/gurpejsingh/Desktop/gpt2-finetune-mac/training-punjabi-gpt/data
Outputs dir: /Users/gurpejsingh/Desktop/gpt2-finetune-mac/training-punjabi-gpt/outputs

## find parquet file

In [4]:
parquet_files = sorted(data_dir.glob("sangraha_pan_guru_chunk_*.parquet"))[:2]

print(f"Using {len(parquet_files)} parquet files")
for f in parquet_files:
    print(f.name)

Using 2 parquet files
sangraha_pan_guru_chunk_001.parquet
sangraha_pan_guru_chunk_002.parquet

## load parquet(dataset) files

In [5]:
dfs = []
for f in parquet_files:
    df = pd.read_parquet(f)
    df["source_file"] = f.name
    dfs.append(df)

corpus_df = pd.concat(dfs, ignore_index=True)

print("Total rows loaded:", len(corpus_df))
print("Columns:", list(corpus_df.columns))
corpus_df.head()

Total rows loaded: 200000
Columns: ['doc_id', 'text', 'source_file']

,doc_id,text,source_file
0,00dcfc410834fbffaee8237168836c05f954d096b70120...,\n1891 ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਦੀ ਸੀਨੇਟ ਚੋਣਾਂ\n\nਸੰਯ...,sangraha_pan_guru_chunk_001.parquet
1,65136cb874e94ef12b412c5e766dd3e23647c48d95e4ff...,\nਫਲੇਵੋਨੋਲ-3-ਓ-ਟ੍ਰਿਗਲੂਕੋਸਾਈਡ ਓ-ਕੌਮਾਰੋਲ ਟ੍ਰਾਂਸਫ...,sangraha_pan_guru_chunk_001.parquet
2,754867d0d7241ad129af50e788055d55d799d0e473ce67...,\nਪ੍ਰਸੰਨਾ ਪੇਓ\n\nਏਅਰ ਵਾਈਸ-ਮਾਰਸ਼ਲ ਐੱਮ. ਡੀ. ਏ. ਪ...,sangraha_pan_guru_chunk_001.parquet
3,8c734a639f9a32178d2ad246b8781a6f03bc1c5315265c...,"\nਤੰਗਖੁਲ ਲੋਕ\n\nਤੰਗਖੁਲ ਲੋਕ, ਜਿਨ੍ਹਾਂ ਨੂੰ ਤੰਗਖੁਲ...",sangraha_pan_guru_chunk_001.parquet
4,09647d359e8ece9593a88d8292fb654a3c725c199a1996...,\nਸਾਈਨਾਸ (ਕ੍ਰੇਟਰ)\n\nਸਾਇਨਾਸ ਇੱਕ ਛੋਟਾ ਚੰਦਰ ਪ੍ਰਭ...,sangraha_pan_guru_chunk_001.parquet

## inspect sample row

In [6]:
for i in range(3):
    print(f"\n--- Row {i+1} ---")
    print(corpus_df.iloc[i].to_dict())

--- Row 1 ---
{'doc_id': '00dcfc410834fbffaee8237168836c05f954d096b701206b5f8f164487608510', 'text': "\n1891 ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਦੀ ਸੀਨੇਟ ਚੋਣਾਂ\n\nਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਦੀ ਸੈਨੇਟ ਚੋਣਾਂ 20 ਅਤੇ 21 ਜਨਵਰੀ 1891 ਨੂੰ ਨਿਊਯਾਰਕ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੁਆਰਾ ਇੱਕ ਯੂ ਦੀ ਚੋਣ ਕਰਨ ਲਈ ਆਯੋਜਿਤ ਕੀਤੀਆਂ ਗਈਆਂ ਸਨ।ਐਸ. ਸੈਨੇਟਰ (ਕਲਾਸ 3), ਸੰਯੁਕਤ ਰਾਜ ਦੀ ਸੀਨੇਟ ਵਿੱਚ ਨਿਊਯਾਰਕ ਰਾਜ ਦੀ ਨੁਮਾਇੰਦਗੀ ਕਰਨ ਲਈ।\nਪਿਛੋਕਡ਼.\nਰਿਪਬਲਿਕਨ ਵਿਲੀਅਮ ਐਮ. ਈਵਾਰਟਸ 1885 ਵਿੱਚ ਇਸ ਸੀਟ ਲਈ ਚੁਣੇ ਗਏ ਸਨ ਅਤੇ ਉਨ੍ਹਾਂ ਦਾ ਕਾਰਜਕਾਲ 3 ਮਾਰਚ 1891 ਨੂੰ ਖਤਮ ਹੋ ਰਿਹਾ ਸੀ।\nਨਵੰਬਰ 1889 ਵਿੱਚ ਰਾਜ ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ, ਰਾਜ ਦੀ ਸੀਨੇਟ ਵਿੱਚ 19 ਗਣਤੰਤਰ ਅਤੇ 13 ਲੋਕਤੰਤਰੀ ਦੋ ਸਾਲ ਦੇ ਕਾਰਜਕਾਲ (1890-1891) ਲਈ ਚੁਣੇ ਗਏ ਸਨ। ਨਵੰਬਰ 1890 ਵਿੱਚ ਰਾਜ ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ, 68 ਡੈਮੋਕਰੇਟਸ ਅਤੇ 60 ਰਿਪਬਲਿਕਨ 1891 ਦੇ ਸੈਸ਼ਨ ਲਈ ਵਿਧਾਨ ਸਭਾ ਲਈ ਚੁਣੇ ਗਏ ਸਨ। 114ਵੀਂ ਨਿਊਯਾਰਕ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੀ ਮੀਟਿੰਗ 6 ਜਨਵਰੀ ਤੋਂ 30 ਅਪ੍ਰੈਲ 1891 ਤੱਕ ਅਲਬਾਨੀ, ਨਿਊਯਾਰਕ ਵਿਖੇ ਹੋਈ।\nਉਮੀਦਵਾਰ।\nਸਮਿਥ ਮਿਡ ਵੀਡ 1890 ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ ਵਿਧਾਨ ਸਭਾ ਦੇ ਨਿਯੰਤਰਣ ਦਾ ਦਾਅਵਾ ਕਰਨ ਦੇ ਜਮਹੂਰੀ ਯਤਨ ਦਾ ਇੱਕ ਪ੍ਰਮੁੱਖ ਪ੍ਰਬੰਧਕ ਅਤੇ ਵਿੱਤੀ ਸਮਰਥਕ ਸੀ। ਸੀਨੇਟ ਵਿੱਚ ਇੱਕ ਛੋਟੀ ਜਿਹੀ ਘੱਟ ਗਿਣਤੀ ਪਰ ਵਿਧਾਨ ਸਭਾ ਵਿੱਚ ਥੋਡ਼੍ਹੀ ਵੱਡੀ ਬਹੁਮਤ ਦੇ ਨਾਲ, ਲੋਕਤੰਤਰੀ ਵਿਧਾਨ ਸਭਾ ਦੇ ਸਾਂਝੇ ਬੈਲਟ ਉੱਤੇ ਆਪਣੇ ਆਪ ਵਿੱਚੋਂ ਇੱਕ ਨੂੰ ਚੁਣਨ ਲਈ ਸਥਿਤੀ ਵਿੱਚ ਸਨ। ਜੰਗਲੀ ਬੂਟੀ ਦੇ ਜਮਹੂਰੀ ਉਮੀਦਵਾਰ ਬਣਨ ਦੀ ਉਮੀਦ ਸੀ, ਪਰ ਜੇਕਰ ਗਵਰਨਰ ਡੇਵਿਡ ਬੀ. ਪਹਾਡ਼ੀ ਨਾਮਜ਼ਦਗੀ ਚਾਹੁੰਦਾ ਸੀ। ਪਹਾਡ਼ੀ ਨੇ ਭੱਜਣ ਦਾ ਫੈਸਲਾ ਕੀਤਾ ਅਤੇ ਬੂਟੀ ਵਾਪਸ ਲੈ ਲਈ। ਜਦੋਂ 19 ਜਨਵਰੀ ਨੂੰ ਜਮਹੂਰੀ ਕਾਕਸ ਦੀ ਮੀਟਿੰਗ ਹੋਈ, ਤਾਂ ਰਾਜ ਦੇ 74 ਵਿਧਾਨ ਸਭਾ ਮੈਂਬਰਾਂ ਨੇ ਹਿੱਸਾ ਲਿਆ, ਅਤੇ ਰਾਜ ਦੇ ਸੈਨੇਟਰ ਜੌਹਨ ਸੀ. ਜੈਕੌਬਸ ਨੇ ਪ੍ਰਧਾਨਗੀ ਕੀਤੀ। ਗਵਰਨਰ ਡੇਵਿਡ ਬੀ. ਪਹਾਡ਼ੀ ਨੂੰ ਪ੍ਰਸ਼ੰਸਾ ਦੁਆਰਾ ਨਾਮਜ਼ਦ ਕੀਤਾ ਗਿਆ ਸੀ।\nਜਮਹੂਰੀ ਕਾਕਸ ਦੇ ਖਤਮ ਹੋਣ ਤੋਂ ਤੁਰੰਤ ਬਾਅਦ ਰਿਪਬਲਿਕਨ ਕਾਕਸ ਦੀ ਮੀਟਿੰਗ ਹੋਈ, ਅਸੈਂਬਲੀਮੈਨ ਜੇਮਜ਼ ਡਬਲਯੂ. ਹਸਟਡ ਨੇ ਪ੍ਰਧਾਨਗੀ ਕੀਤੀ। ਉਨ੍ਹਾਂ ਨੇ ਮੌਜੂਦਾ ਯੂ ਨੂੰ ਦੁਬਾਰਾ ਨਾਮਜ਼ਦ ਕੀਤਾ।ਐਸ. ਸੈਨੇਟਰ ਵਿਲੀਅਮ ਐਮ. ਸਰਬਸੰਮਤੀ ਨਾਲ ਬਚ ਜਾਂਦਾ ਹੈ।\nਨਤੀਜਾ।\n20 ਜਨਵਰੀ ਨੂੰ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੇ ਦੋਵੇਂ ਸਦਨਾਂ ਨੇ ਵੱਖਰੇ ਤੌਰ 'ਤੇ ਵੋਟ ਪਾਈਆਂ। ਅਹੁਦੇਦਾਰ ਯੂ.ਐਸ. ਸੈਨੇਟਰ ਈਵਾਰਟਸ ਰਾਜ ਦੀ ਸੀਨੇਟ, ਸਰਕਾਰ ਦੀ ਚੋਣ ਸੀ। ਪਹਾਡ਼ੀ ਵਿਧਾਨ ਸਭਾ ਦੀ ਚੋਣ ਹੈ। 21 ਜਨਵਰੀ ਨੂੰ, ਦੋਵੇਂ ਸਦਨ ਸਾਂਝੇ ਸੈਸ਼ਨ ਵਿੱਚ ਮਿਲੇ, ਅਤੇ ਨਾਮਜ਼ਦਗੀਆਂ ਦੀ ਤੁਲਨਾ ਕਰਦੇ ਹੋਏ, ਪਾਇਆ ਕਿ ਉਹ ਅਸਹਿਮਤ ਸਨ ਅਤੇ ਇੱਕ ਸਾਂਝੇ ਵੋਟ ਲਈ ਅੱਗੇ ਵਧੇ। ਸਰਕਾਰ. ਹਿਲ ਨੂੰ 2 ਦੇ ਬਹੁਮਤ ਨਾਲ ਚੁਣਿਆ ਗਿਆ ਸੀ, ਵਿਧਾਨ ਸਭਾ ਦਾ ਹਰ ਮੈਂਬਰ ਮੌਜੂਦ ਸੀ।\nਇਸ ਦੇ ਬਾਅਦ.\nਇਹ ਸੀਟ 4 ਮਾਰਚ 1891 ਨੂੰ ਖਾਲੀ ਹੋ ਗਈ ਸੀ। ਹਿਲ 31 ਦਸੰਬਰ, 1891 ਤੱਕ ਨਿਊਯਾਰਕ ਦੇ ਗਵਰਨਰ ਦੇ ਅਹੁਦੇ ਉੱਤੇ ਰਹੇ ਅਤੇ 7 ਜਨਵਰੀ, 1892 ਨੂੰ ਹੀ ਆਪਣੀ ਸੀਟ ਸੰਭਾਲੀ, ਅਸਲ ਵਿੱਚ ਸਿਰਫ਼ ਇੱਕ ਮਹੀਨੇ ਦਾ ਸੈਸ਼ਨ ਨਹੀਂ ਸੀ। 52ਵੀਂ ਸੰਯੁਕਤ ਰਾਜ ਕਾਂਗਰਸ ਦੌਰਾਨ ਕੋਈ ਵਿਸ਼ੇਸ਼ ਸੈਸ਼ਨ ਨਹੀਂ ਸਨ ਅਤੇ ਨਿਯਮਤ ਸੈਸ਼ਨ ਸਿਰਫ 7 ਦਸੰਬਰ, 1891 ਨੂੰ ਸ਼ੁਰੂ ਹੋਇਆ. ਹਿਲ ਨੇ ਇੱਕ ਕਾਰਜਕਾਲ ਦੀ ਸੇਵਾ ਕੀਤੀ, ਅਤੇ ਯੂ. ਐੱਸ. ਵਿੱਚ ਰਿਹਾ।ਐਸ. 3 ਮਾਰਚ, 1897 ਤੱਕ ਸੀਨੇਟ. ਜਨਵਰੀ 1897 ਵਿੱਚ, ਹਿਲ ਨੂੰ ਰਿਪਬਲਿਕਨ ਥਾਮਸ ਸੀ ਦੁਆਰਾ ਦੁਬਾਰਾ ਚੋਣ ਲਈ ਹਰਾਇਆ ਗਿਆ ਸੀ। ਪਲੈਟ ਜੋ ਕਿ ਯੂ ਸੀ।ਐਸ. ਸੰਖੇਪ ਵਿੱਚ ਸੈਨੇਟਰ 1881 ਵਿੱਚ।\n\n", 'source_file': 'sangraha_pan_guru_chunk_001.parquet'}

--- Row 2 ---
{'doc_id': '65136cb874e94ef12b412c5e766dd3e23647c48d95e4ff0deb93f18f5b9324b7', 'text': "\nਫਲੇਵੋਨੋਲ-3-ਓ-ਟ੍ਰਿਗਲੂਕੋਸਾਈਡ ਓ-ਕੌਮਾਰੋਲ ਟ੍ਰਾਂਸਫਰੇਸ\n\nਇਨਜ਼ਾਈਮੋਲੋਜੀ ਵਿੱਚ, ਇੱਕ ਫਲੇਵੋਨੋਲ-3-ਓ-ਟ੍ਰਿਗਲੂਕੋਸਾਈਡ ਓ-ਕੌਮਾਰੋਲਟ੍ਰਾਂਸਫਰੇਸ () ਇੱਕ ਐਨਜ਼ਾਈਮ ਹੈ ਜੋ ਰਸਾਇਣਕ ਪ੍ਰਤੀਕ੍ਰਿਆ ਨੂੰ ਉਤਪ੍ਰੇਰਿਤ ਕਰਦਾ ਹੈ।\nਇਸ ਐਂਜ਼ਾਈਮ ਦੇ 3 ਘਟਾਓਣਾ 4-ਕੌਮਰੌਇਲ-ਕੋਆ, ਫਲੇਵੋਨੋਲ, ਅਤੇ 3-ਓ-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਾਈਡ ਹਨ, ਜਦੋਂ ਕਿ ਇਸ ਦੇ 4 ਉਤਪਾਦ ਕੋਆ, ਫਲੇਵੋਨੋਲ, 3-ਓ-[6-(4-ਕੌਮਰੌਇਲ)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-, ਅਤੇ ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਾਈਡ ਹਨ।\nਇਹ ਐਂਜ਼ਾਈਮ ਟ੍ਰਾਂਸਫਰਜ਼ ਦੇ ਪਰਿਵਾਰ ਨਾਲ ਸਬੰਧਤ ਹੈ, ਖਾਸ ਤੌਰ 'ਤੇ ਉਹ ਐਸਾਈਲਟ੍ਰਾਂਸਫਰੇਸ ਜੋ ਅਮੀਨੋਸਿਲ ਸਮੂਹਾਂ ਤੋਂ ਇਲਾਵਾ ਸਮੂਹਾਂ ਨੂੰ ਤਬਦੀਲ ਕਰਦੇ ਹਨ। ਇਸ ਐਂਜ਼ਾਈਮ ਕਲਾਸ ਦਾ ਯੋਜਨਾਬੱਧ ਨਾਮ 4-ਕੌਮਰੌਇਲ-ਕੋਆ ਹੈਃ ਫਲੇਵੋਨੋਲ-3-ਓ-[ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਡ ਈ] 6-ਓ-4-ਕੌਮਰੌਇਲ ਟ੍ਰਾਂਸਫਰੇਸ ਹੈ।\n\n", 'source_file': 'sangraha_pan_guru_chunk_001.parquet'}

--- Row 3 ---
{'doc_id': '754867d0d7241ad129af50e788055d55d799d0e473ce67e826974017cfe24cd8', 'text': '\nਪ੍ਰਸੰਨਾ ਪੇਓ\n\nਏਅਰ ਵਾਈਸ-ਮਾਰਸ਼ਲ ਐੱਮ. ਡੀ. ਏ. ਪ੍ਰਸੰਨਾ ਪਾਯੋ (ਜਿਸ ਨੂੰ ਏਵੀਐਮ ਪ੍ਰਸੰਤਾ ਪਾਯੋ ਵੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ) ਸ਼੍ਰੀਲੰਕਾ ਹਵਾਈ ਸੈਨਾ ਦਾ ਇੱਕ ਸੇਵਾਮੁਕਤ ਹਵਾਈ ਅਧਿਕਾਰੀ ਹੈ ਜਿਸ ਨੇ ਸ਼੍ਰੀਲੰਕਾ ਹਵਾਈ ਸੈਨਾ ਦੇ ਚੀਫ਼ ਆਫ਼ ਸਟਾਫ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਈ। ਇਸ ਨਿਯੁਕਤੀ ਤੋਂ ਪਹਿਲਾਂ, ਉਨ੍ਹਾਂ ਨੇ ਡਾਇਰੈਕਟਰ ਸਿਖਲਾਈ ਅਤੇ ਡਾਇਰੈਕਟਰ ਹਵਾਈ ਸੰਚਾਲਨ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਈ। ਉਨ੍ਹਾਂ ਨੇ ਸ਼੍ਰੀਲੰਕਾ ਦੇ ਸਭ ਤੋਂ ਵੱਡੇ ਹਵਾਈ ਸੈਨਾ ਅੱਡੇ, ਕਤੁਨਾਇਕੇ ਦੇ ਬੇਸ ਕਮਾਂਡਰ ਵਜੋਂ ਵੀ ਸੇਵਾ ਨਿਭਾਈ।\nਮੁਢਲਾ ਜੀਵਨ ਅਤੇ ਸਿੱਖਿਆ।\nਪੇਓ ਨੇ ਆਪਣੀ ਪਡ਼੍ਹਾਈ ਐਸ. ਏ. ਵਿੱਚ ਪੂਰੀ ਕੀਤੀ। ਥਾਮਸ ਕਾਲਜ, ਬੰਦਾਰਾਵੇਲਾ। ਫਿਰ ਉਹ 1985 ਵਿੱਚ ਜਨਰਲ ਡਿਊਟੀਜ਼ ਪਾਇਲਟ ਸ਼ਾਖਾ ਵਿੱਚ ਸ਼੍ਰੀਲੰਕਾਈ ਹਵਾਈ ਸੈਨਾ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਏ। ਉਹ ਰੱਖਿਆ ਸੇਵਾਵਾਂ ਕਮਾਂਡ ਅਤੇ ਸਟਾਫ ਕਾਲਜ ਸਪੁਗਾਸਕਾਂਡਾ, ਸ਼੍ਰੀਲੰਕਾ ਤੋਂ ਗ੍ਰੈਜੂਏਟ ਹੈ ਅਤੇ ਰਾਸ਼ਟਰੀ ਰੱਖਿਆ ਯੂਨੀਵਰਸਿਟੀ, ਪਾਕਿਸਤਾਨ ਤੋਂ ਐੱਨ. ਡੀ. ਸੀ. ਪੂਰੀ ਕੀਤੀ ਹੈ।\nਹਵਾਈ ਸੈਨਾ ਕੈਰੀਅਰ.\nਉਨ੍ਹਾਂ ਨੇ ਰੂਸ ਫੈਡਰੇਸ਼ਨ ਵਿੱਚ ਰੱਖਿਆ ਅਟੈਚੀ ਵਜੋਂ ਵੀ ਕੰਮ ਕੀਤਾ। ਏ. ਵੀ. ਐੱਮ. ਵਜੋਂ ਤਰੱਕੀ ਮਿਲਣ ਤੋਂ ਬਾਅਦ ਉਹ ਰੱਖਿਆ ਖੋਜ ਕੇਂਦਰ ਦੇ ਡਾਇਰੈਕਟਰ ਜਨਰਲ ਬਣੇ। ਉਹ 12 ਸਤੰਬਰ, 2022 ਨੂੰ ਸਲੈਫ ਦੇ ਚੀਫ਼ ਆਫ਼ ਸਟਾਫ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਉਂਦੇ ਹੋਏ ਸਰਗਰਮ ਸੇਵਾ ਤੋਂ ਸੇਵਾਮੁਕਤ ਹੋਏ।\n\n', 'source_file': 'sangraha_pan_guru_chunk_001.parquet'}

## check null or duplicate value

In [6]:
print("Null counts:")
print(corpus_df.isnull().sum())

print("\nDuplicate doc_id count:")
if "doc_id" in corpus_df.columns:
    print(corpus_df["doc_id"].duplicated().sum())
else:
    print("No doc_id column found")

Null counts:
doc_id         0
text           0
source_file    0
dtype: int64

Duplicate doc_id count:
12437

## basic cleaning helper text

In [7]:
def clean_text(text: str) -> str:
    if pd.isna(text):
        return ""
    
    text = str(text)

    # Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Remove excessive spaces/tabs
    text = re.sub(r"[ \t]+", " ", text)

    # Remove too many blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Strip outer whitespace
    text = text.strip()

    return text


def is_gurmukhi_char(ch: str) -> bool:
    # Unicode block for Gurmukhi: U+0A00 to U+0A7F
    return "\u0A00" <= ch <= "\u0A7F"


def gurmukhi_ratio(text: str) -> float:
    if not text:
        return 0.0
    
    chars = [ch for ch in text if not ch.isspace()]
    if not chars:
        return 0.0
    
    gurmukhi_count = sum(1 for ch in chars if is_gurmukhi_char(ch))
    return gurmukhi_count / len(chars)

## apply cleaning

In [8]:
corpus_df["text"] = corpus_df["text"].apply(clean_text)

print("After cleaning:")
print(corpus_df["text"].head(3).tolist())

After cleaning:
["1891 ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਦੀ ਸੀਨੇਟ ਚੋਣਾਂ\n\nਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਦੀ ਸੈਨੇਟ ਚੋਣਾਂ 20 ਅਤੇ 21 ਜਨਵਰੀ 1891 ਨੂੰ ਨਿਊਯਾਰਕ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੁਆਰਾ ਇੱਕ ਯੂ ਦੀ ਚੋਣ ਕਰਨ ਲਈ ਆਯੋਜਿਤ ਕੀਤੀਆਂ ਗਈਆਂ ਸਨ।ਐਸ. ਸੈਨੇਟਰ (ਕਲਾਸ 3), ਸੰਯੁਕਤ ਰਾਜ ਦੀ ਸੀਨੇਟ ਵਿੱਚ ਨਿਊਯਾਰਕ ਰਾਜ ਦੀ ਨੁਮਾਇੰਦਗੀ ਕਰਨ ਲਈ।\nਪਿਛੋਕਡ਼.\nਰਿਪਬਲਿਕਨ ਵਿਲੀਅਮ ਐਮ. ਈਵਾਰਟਸ 1885 ਵਿੱਚ ਇਸ ਸੀਟ ਲਈ ਚੁਣੇ ਗਏ ਸਨ ਅਤੇ ਉਨ੍ਹਾਂ ਦਾ ਕਾਰਜਕਾਲ 3 ਮਾਰਚ 1891 ਨੂੰ ਖਤਮ ਹੋ ਰਿਹਾ ਸੀ।\nਨਵੰਬਰ 1889 ਵਿੱਚ ਰਾਜ ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ, ਰਾਜ ਦੀ ਸੀਨੇਟ ਵਿੱਚ 19 ਗਣਤੰਤਰ ਅਤੇ 13 ਲੋਕਤੰਤਰੀ ਦੋ ਸਾਲ ਦੇ ਕਾਰਜਕਾਲ (1890-1891) ਲਈ ਚੁਣੇ ਗਏ ਸਨ। ਨਵੰਬਰ 1890 ਵਿੱਚ ਰਾਜ ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ, 68 ਡੈਮੋਕਰੇਟਸ ਅਤੇ 60 ਰਿਪਬਲਿਕਨ 1891 ਦੇ ਸੈਸ਼ਨ ਲਈ ਵਿਧਾਨ ਸਭਾ ਲਈ ਚੁਣੇ ਗਏ ਸਨ। 114ਵੀਂ ਨਿਊਯਾਰਕ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੀ ਮੀਟਿੰਗ 6 ਜਨਵਰੀ ਤੋਂ 30 ਅਪ੍ਰੈਲ 1891 ਤੱਕ ਅਲਬਾਨੀ, ਨਿਊਯਾਰਕ ਵਿਖੇ ਹੋਈ।\nਉਮੀਦਵਾਰ।\nਸਮਿਥ ਮਿਡ ਵੀਡ 1890 ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ ਵਿਧਾਨ ਸਭਾ ਦੇ ਨਿਯੰਤਰਣ ਦਾ ਦਾਅਵਾ ਕਰਨ ਦੇ ਜਮਹੂਰੀ ਯਤਨ ਦਾ ਇੱਕ ਪ੍ਰਮੁੱਖ ਪ੍ਰਬੰਧਕ ਅਤੇ ਵਿੱਤੀ ਸਮਰਥਕ ਸੀ। ਸੀਨੇਟ ਵਿੱਚ ਇੱਕ ਛੋਟੀ ਜਿਹੀ ਘੱਟ ਗਿਣਤੀ ਪਰ ਵਿਧਾਨ ਸਭਾ ਵਿੱਚ ਥੋਡ਼੍ਹੀ ਵੱਡੀ ਬਹੁਮਤ ਦੇ ਨਾਲ, ਲੋਕਤੰਤਰੀ ਵਿਧਾਨ ਸਭਾ ਦੇ ਸਾਂਝੇ ਬੈਲਟ ਉੱਤੇ ਆਪਣੇ ਆਪ ਵਿੱਚੋਂ ਇੱਕ ਨੂੰ ਚੁਣਨ ਲਈ ਸਥਿਤੀ ਵਿੱਚ ਸਨ। ਜੰਗਲੀ ਬੂਟੀ ਦੇ ਜਮਹੂਰੀ ਉਮੀਦਵਾਰ ਬਣਨ ਦੀ ਉਮੀਦ ਸੀ, ਪਰ ਜੇਕਰ ਗਵਰਨਰ ਡੇਵਿਡ ਬੀ. ਪਹਾਡ਼ੀ ਨਾਮਜ਼ਦਗੀ ਚਾਹੁੰਦਾ ਸੀ। ਪਹਾਡ਼ੀ ਨੇ ਭੱਜਣ ਦਾ ਫੈਸਲਾ ਕੀਤਾ ਅਤੇ ਬੂਟੀ ਵਾਪਸ ਲੈ ਲਈ। ਜਦੋਂ 19 ਜਨਵਰੀ ਨੂੰ ਜਮਹੂਰੀ ਕਾਕਸ ਦੀ ਮੀਟਿੰਗ ਹੋਈ, ਤਾਂ ਰਾਜ ਦੇ 74 ਵਿਧਾਨ ਸਭਾ ਮੈਂਬਰਾਂ ਨੇ ਹਿੱਸਾ ਲਿਆ, ਅਤੇ ਰਾਜ ਦੇ ਸੈਨੇਟਰ ਜੌਹਨ ਸੀ. ਜੈਕੌਬਸ ਨੇ ਪ੍ਰਧਾਨਗੀ ਕੀਤੀ। ਗਵਰਨਰ ਡੇਵਿਡ ਬੀ. ਪਹਾਡ਼ੀ ਨੂੰ ਪ੍ਰਸ਼ੰਸਾ ਦੁਆਰਾ ਨਾਮਜ਼ਦ ਕੀਤਾ ਗਿਆ ਸੀ।\nਜਮਹੂਰੀ ਕਾਕਸ ਦੇ ਖਤਮ ਹੋਣ ਤੋਂ ਤੁਰੰਤ ਬਾਅਦ ਰਿਪਬਲਿਕਨ ਕਾਕਸ ਦੀ ਮੀਟਿੰਗ ਹੋਈ, ਅਸੈਂਬਲੀਮੈਨ ਜੇਮਜ਼ ਡਬਲਯੂ. ਹਸਟਡ ਨੇ ਪ੍ਰਧਾਨਗੀ ਕੀਤੀ। ਉਨ੍ਹਾਂ ਨੇ ਮੌਜੂਦਾ ਯੂ ਨੂੰ ਦੁਬਾਰਾ ਨਾਮਜ਼ਦ ਕੀਤਾ।ਐਸ. ਸੈਨੇਟਰ ਵਿਲੀਅਮ ਐਮ. ਸਰਬਸੰਮਤੀ ਨਾਲ ਬਚ ਜਾਂਦਾ ਹੈ।\nਨਤੀਜਾ।\n20 ਜਨਵਰੀ ਨੂੰ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੇ ਦੋਵੇਂ ਸਦਨਾਂ ਨੇ ਵੱਖਰੇ ਤੌਰ 'ਤੇ ਵੋਟ ਪਾਈਆਂ। ਅਹੁਦੇਦਾਰ ਯੂ.ਐਸ. ਸੈਨੇਟਰ ਈਵਾਰਟਸ ਰਾਜ ਦੀ ਸੀਨੇਟ, ਸਰਕਾਰ ਦੀ ਚੋਣ ਸੀ। ਪਹਾਡ਼ੀ ਵਿਧਾਨ ਸਭਾ ਦੀ ਚੋਣ ਹੈ। 21 ਜਨਵਰੀ ਨੂੰ, ਦੋਵੇਂ ਸਦਨ ਸਾਂਝੇ ਸੈਸ਼ਨ ਵਿੱਚ ਮਿਲੇ, ਅਤੇ ਨਾਮਜ਼ਦਗੀਆਂ ਦੀ ਤੁਲਨਾ ਕਰਦੇ ਹੋਏ, ਪਾਇਆ ਕਿ ਉਹ ਅਸਹਿਮਤ ਸਨ ਅਤੇ ਇੱਕ ਸਾਂਝੇ ਵੋਟ ਲਈ ਅੱਗੇ ਵਧੇ। ਸਰਕਾਰ. ਹਿਲ ਨੂੰ 2 ਦੇ ਬਹੁਮਤ ਨਾਲ ਚੁਣਿਆ ਗਿਆ ਸੀ, ਵਿਧਾਨ ਸਭਾ ਦਾ ਹਰ ਮੈਂਬਰ ਮੌਜੂਦ ਸੀ।\nਇਸ ਦੇ ਬਾਅਦ.\nਇਹ ਸੀਟ 4 ਮਾਰਚ 1891 ਨੂੰ ਖਾਲੀ ਹੋ ਗਈ ਸੀ। ਹਿਲ 31 ਦਸੰਬਰ, 1891 ਤੱਕ ਨਿਊਯਾਰਕ ਦੇ ਗਵਰਨਰ ਦੇ ਅਹੁਦੇ ਉੱਤੇ ਰਹੇ ਅਤੇ 7 ਜਨਵਰੀ, 1892 ਨੂੰ ਹੀ ਆਪਣੀ ਸੀਟ ਸੰਭਾਲੀ, ਅਸਲ ਵਿੱਚ ਸਿਰਫ਼ ਇੱਕ ਮਹੀਨੇ ਦਾ ਸੈਸ਼ਨ ਨਹੀਂ ਸੀ। 52ਵੀਂ ਸੰਯੁਕਤ ਰਾਜ ਕਾਂਗਰਸ ਦੌਰਾਨ ਕੋਈ ਵਿਸ਼ੇਸ਼ ਸੈਸ਼ਨ ਨਹੀਂ ਸਨ ਅਤੇ ਨਿਯਮਤ ਸੈਸ਼ਨ ਸਿਰਫ 7 ਦਸੰਬਰ, 1891 ਨੂੰ ਸ਼ੁਰੂ ਹੋਇਆ. ਹਿਲ ਨੇ ਇੱਕ ਕਾਰਜਕਾਲ ਦੀ ਸੇਵਾ ਕੀਤੀ, ਅਤੇ ਯੂ. ਐੱਸ. ਵਿੱਚ ਰਿਹਾ।ਐਸ. 3 ਮਾਰਚ, 1897 ਤੱਕ ਸੀਨੇਟ. ਜਨਵਰੀ 1897 ਵਿੱਚ, ਹਿਲ ਨੂੰ ਰਿਪਬਲਿਕਨ ਥਾਮਸ ਸੀ ਦੁਆਰਾ ਦੁਬਾਰਾ ਚੋਣ ਲਈ ਹਰਾਇਆ ਗਿਆ ਸੀ। ਪਲੈਟ ਜੋ ਕਿ ਯੂ ਸੀ।ਐਸ. ਸੰਖੇਪ ਵਿੱਚ ਸੈਨੇਟਰ 1881 ਵਿੱਚ।", "ਫਲੇਵੋਨੋਲ-3-ਓ-ਟ੍ਰਿਗਲੂਕੋਸਾਈਡ ਓ-ਕੌਮਾਰੋਲ ਟ੍ਰਾਂਸਫਰੇਸ\n\nਇਨਜ਼ਾਈਮੋਲੋਜੀ ਵਿੱਚ, ਇੱਕ ਫਲੇਵੋਨੋਲ-3-ਓ-ਟ੍ਰਿਗਲੂਕੋਸਾਈਡ ਓ-ਕੌਮਾਰੋਲਟ੍ਰਾਂਸਫਰੇਸ () ਇੱਕ ਐਨਜ਼ਾਈਮ ਹੈ ਜੋ ਰਸਾਇਣਕ ਪ੍ਰਤੀਕ੍ਰਿਆ ਨੂੰ ਉਤਪ੍ਰੇਰਿਤ ਕਰਦਾ ਹੈ।\nਇਸ ਐਂਜ਼ਾਈਮ ਦੇ 3 ਘਟਾਓਣਾ 4-ਕੌਮਰੌਇਲ-ਕੋਆ, ਫਲੇਵੋਨੋਲ, ਅਤੇ 3-ਓ-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਾਈਡ ਹਨ, ਜਦੋਂ ਕਿ ਇਸ ਦੇ 4 ਉਤਪਾਦ ਕੋਆ, ਫਲੇਵੋਨੋਲ, 3-ਓ-[6-(4-ਕੌਮਰੌਇਲ)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-, ਅਤੇ ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਾਈਡ ਹਨ।\nਇਹ ਐਂਜ਼ਾਈਮ ਟ੍ਰਾਂਸਫਰਜ਼ ਦੇ ਪਰਿਵਾਰ ਨਾਲ ਸਬੰਧਤ ਹੈ, ਖਾਸ ਤੌਰ 'ਤੇ ਉਹ ਐਸਾਈਲਟ੍ਰਾਂਸਫਰੇਸ ਜੋ ਅਮੀਨੋਸਿਲ ਸਮੂਹਾਂ ਤੋਂ ਇਲਾਵਾ ਸਮੂਹਾਂ ਨੂੰ ਤਬਦੀਲ ਕਰਦੇ ਹਨ। ਇਸ ਐਂਜ਼ਾਈਮ ਕਲਾਸ ਦਾ ਯੋਜਨਾਬੱਧ ਨਾਮ 4-ਕੌਮਰੌਇਲ-ਕੋਆ ਹੈਃ ਫਲੇਵੋਨੋਲ-3-ਓ-[ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਡ ਈ] 6-ਓ-4-ਕੌਮਰੌਇਲ ਟ੍ਰਾਂਸਫਰੇਸ ਹੈ।", 'ਪ੍ਰਸੰਨਾ ਪੇਓ\n\nਏਅਰ ਵਾਈਸ-ਮਾਰਸ਼ਲ ਐੱਮ. ਡੀ. ਏ. ਪ੍ਰਸੰਨਾ ਪਾਯੋ (ਜਿਸ ਨੂੰ ਏਵੀਐਮ ਪ੍ਰਸੰਤਾ ਪਾਯੋ ਵੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ) ਸ਼੍ਰੀਲੰਕਾ ਹਵਾਈ ਸੈਨਾ ਦਾ ਇੱਕ ਸੇਵਾਮੁਕਤ ਹਵਾਈ ਅਧਿਕਾਰੀ ਹੈ ਜਿਸ ਨੇ ਸ਼੍ਰੀਲੰਕਾ ਹਵਾਈ ਸੈਨਾ ਦੇ ਚੀਫ਼ ਆਫ਼ ਸਟਾਫ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਈ। ਇਸ ਨਿਯੁਕਤੀ ਤੋਂ ਪਹਿਲਾਂ, ਉਨ੍ਹਾਂ ਨੇ ਡਾਇਰੈਕਟਰ ਸਿਖਲਾਈ ਅਤੇ ਡਾਇਰੈਕਟਰ ਹਵਾਈ ਸੰਚਾਲਨ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਈ। ਉਨ੍ਹਾਂ ਨੇ ਸ਼੍ਰੀਲੰਕਾ ਦੇ ਸਭ ਤੋਂ ਵੱਡੇ ਹਵਾਈ ਸੈਨਾ ਅੱਡੇ, ਕਤੁਨਾਇਕੇ ਦੇ ਬੇਸ ਕਮਾਂਡਰ ਵਜੋਂ ਵੀ ਸੇਵਾ ਨਿਭਾਈ।\nਮੁਢਲਾ ਜੀਵਨ ਅਤੇ ਸਿੱਖਿਆ।\nਪੇਓ ਨੇ ਆਪਣੀ ਪਡ਼੍ਹਾਈ ਐਸ. ਏ. ਵਿੱਚ ਪੂਰੀ ਕੀਤੀ। ਥਾਮਸ ਕਾਲਜ, ਬੰਦਾਰਾਵੇਲਾ। ਫਿਰ ਉਹ 1985 ਵਿੱਚ ਜਨਰਲ ਡਿਊਟੀਜ਼ ਪਾਇਲਟ ਸ਼ਾਖਾ ਵਿੱਚ ਸ਼੍ਰੀਲੰਕਾਈ ਹਵਾਈ ਸੈਨਾ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਏ। ਉਹ ਰੱਖਿਆ ਸੇਵਾਵਾਂ ਕਮਾਂਡ ਅਤੇ ਸਟਾਫ ਕਾਲਜ ਸਪੁਗਾਸਕਾਂਡਾ, ਸ਼੍ਰੀਲੰਕਾ ਤੋਂ ਗ੍ਰੈਜੂਏਟ ਹੈ ਅਤੇ ਰਾਸ਼ਟਰੀ ਰੱਖਿਆ ਯੂਨੀਵਰਸਿਟੀ, ਪਾਕਿਸਤਾਨ ਤੋਂ ਐੱਨ. ਡੀ. ਸੀ. ਪੂਰੀ ਕੀਤੀ ਹੈ।\nਹਵਾਈ ਸੈਨਾ ਕੈਰੀਅਰ.\nਉਨ੍ਹਾਂ ਨੇ ਰੂਸ ਫੈਡਰੇਸ਼ਨ ਵਿੱਚ ਰੱਖਿਆ ਅਟੈਚੀ ਵਜੋਂ ਵੀ ਕੰਮ ਕੀਤਾ। ਏ. ਵੀ. ਐੱਮ. ਵਜੋਂ ਤਰੱਕੀ ਮਿਲਣ ਤੋਂ ਬਾਅਦ ਉਹ ਰੱਖਿਆ ਖੋਜ ਕੇਂਦਰ ਦੇ ਡਾਇਰੈਕਟਰ ਜਨਰਲ ਬਣੇ। ਉਹ 12 ਸਤੰਬਰ, 2022 ਨੂੰ ਸਲੈਫ ਦੇ ਚੀਫ਼ ਆਫ਼ ਸਟਾਫ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਉਂਦੇ ਹੋਏ ਸਰਗਰਮ ਸੇਵਾ ਤੋਂ ਸੇਵਾਮੁਕਤ ਹੋਏ।']

## compute text stats

In [9]:
corpus_df["char_len"] = corpus_df["text"].apply(len)
corpus_df["word_len"] = corpus_df["text"].apply(lambda x: len(x.split()))
corpus_df["line_count"] = corpus_df["text"].apply(lambda x: x.count("\n") + 1 if x else 0)
corpus_df["gurmukhi_ratio"] = corpus_df["text"].apply(gurmukhi_ratio)

corpus_df[["char_len", "word_len", "line_count", "gurmukhi_ratio"]].describe()

            char_len       word_len     line_count  gurmukhi_ratio
count  200000.000000  200000.000000  200000.000000   200000.000000
mean     2919.233825     550.771520      12.939405        0.915620
std      5476.811389    1041.447164      17.235922        0.061456
min        10.000000       3.000000       1.000000        0.049478
25%       590.000000     109.000000       5.000000        0.907609
50%      1369.000000     255.000000       9.000000        0.930699
75%      3073.000000     579.000000      15.000000        0.946902
max    213037.000000   39414.000000    2071.000000        0.991922

## inspect distribution of bad rows

In [11]:
print("Rows with empty text:", (corpus_df["char_len"] == 0).sum())
print("Rows with char_len < 20:", (corpus_df["char_len"] < 20).sum())
print("Rows with word_len < 3:", (corpus_df["word_len"] < 3).sum())
print("Rows with gurmukhi_ratio < 0.5:", (corpus_df["gurmukhi_ratio"] < 0.5).sum())

Rows with empty text: 0
Rows with char_len < 20: 2746
Rows with word_len < 3: 0
Rows with gurmukhi_ratio < 0.5: 464

## preview suspicious row

In [12]:
bad_samples = corpus_df[
    (corpus_df["char_len"] < 20) |
    (corpus_df["word_len"] < 3) |
    (corpus_df["gurmukhi_ratio"] < 0.5)
]

print("Suspicious rows:", len(bad_samples))

for i in range(min(10, len(bad_samples))):
    row = bad_samples.iloc[i]
    print(f"\n--- Suspicious Sample {i+1} ---")
    print("doc_id:", row.get("doc_id", "N/A"))
    print("char_len:", row["char_len"])
    print("word_len:", row["word_len"])
    print("gurmukhi_ratio:", row["gurmukhi_ratio"])
    print("text:", row["text"][:500])

Suspicious rows: 2894

--- Suspicious Sample 1 ---
doc_id: 183c632e85201b88be2b903c7e6d7ca6cfa45488c52c7515ecf8caa0b2e6bfdc
char_len: 15
word_len: 4
gurmukhi_ratio: 0.6666666666666666
text: ਆਰ. ਯੂ. ਐੱਲ. ਈ.

--- Suspicious Sample 2 ---
doc_id: 8412dffe0ba1f9af5aa4f749d58a09229d7a065ae3a3130d95e60f26924bcbb0
char_len: 17
word_len: 4
gurmukhi_ratio: 0.7857142857142857
text: ਐਚ. ਐਮ. ਐਸ. ਨੈਲਸਨ

--- Suspicious Sample 3 ---
doc_id: 83bb1d8cc3e91f17113e3430e0334643b8cbf0ef9a55adc89f15e6a3a9050cc5
char_len: 17
word_len: 4
gurmukhi_ratio: 0.7857142857142857
text: ਆਰ. ਟੀ. ਐੱਲ. ਮਾਰਕ

--- Suspicious Sample 4 ---
doc_id: b71e69e6b07de0c861e4ee4b08e44c8f4dcbcf8d6b79d8f5ffe0ce7f03c33ca5
char_len: 19
word_len: 4
gurmukhi_ratio: 0.375
text: ਆਈ. ਐੱਮ. ਓ. 8640234

--- Suspicious Sample 5 ---
doc_id: 2186018d04fb4b61cc8b889d8ec6d6ebc55f5e4bbf7b507d1b6f5c0bbf8cf1da
char_len: 16
word_len: 4
gurmukhi_ratio: 0.6923076923076923
text: ਐੱਸ. ਡੀ. ਪੀ. ਬੀ.

--- Suspicious Sample 6 ---
doc_id: fe2a78a137cb3647733f6b496cd4d020eb41c8ed89c9333eed9714852424fdd3
char_len: 17
word_len: 4
gurmukhi_ratio: 0.7142857142857143
text: ਐੱਸ. ਵੀ. ਬੀ. ਐੱਮ.

--- Suspicious Sample 7 ---
doc_id: fdd72d3992def5911b0578b04fc2d806a7628c20af44a150bd1dbabbbcf4d9cd
char_len: 20
word_len: 5
gurmukhi_ratio: 0.4375
text: ਐਸ. ਆਰ. 217 (ਏ. ਜ਼.)

--- Suspicious Sample 8 ---
doc_id: dbe8521ab703348975ed12b86101d9028efda804c1af5146a4aac140e050ff4b
char_len: 18
word_len: 4
gurmukhi_ratio: 0.8
text: ਵੀ. ਐੱਚ. ਐੱਫ. ਹੈਲੋ

--- Suspicious Sample 9 ---
doc_id: 71bdf05603ac28b14d8e145208bbcb190aab43498aaff1fb9d062046b6e4c350
char_len: 17
word_len: 4
gurmukhi_ratio: 0.6428571428571429
text: .ਡੀ. ਐੱਮ. ਆਰ. ਸੀ.

--- Suspicious Sample 10 ---
doc_id: 1185e8a69573140d27d54317b622c5eb227e1b991de8dbf43b43d48fd9424009
char_len: 14
word_len: 4
gurmukhi_ratio: 0.6363636363636364
text: ਈ. ਪੀ. ਬੀ. ਸੀ.

## filter corpus

In [13]:
filtered_df = corpus_df[
    (corpus_df["char_len"] >= 30) &
    (corpus_df["word_len"] >= 5) &
    (corpus_df["gurmukhi_ratio"] >= 0.5)
].copy()

print("Original rows:", len(corpus_df))
print("Filtered rows:", len(filtered_df))
print("Removed rows:", len(corpus_df) - len(filtered_df))

Original rows: 200000
Filtered rows: 193028
Removed rows: 6972

## remove exact duplicate rows

In [14]:
before_dedup = len(filtered_df)
filtered_df = filtered_df.drop_duplicates(subset=["text"]).copy()
after_dedup = len(filtered_df)

print("Before dedup:", before_dedup)
print("After dedup:", after_dedup)
print("Removed duplicates:", before_dedup - after_dedup)

Before dedup: 193028
After dedup: 193009
Removed duplicates: 19

## final corpus stats

In [15]:
total_docs = len(filtered_df)
total_chars = filtered_df["char_len"].sum()
total_words = filtered_df["word_len"].sum()
avg_chars = filtered_df["char_len"].mean()
avg_words = filtered_df["word_len"].mean()

print("Final corpus stats")
print("------------------")
print("Documents:", total_docs)
print("Total characters:", f"{total_chars:,}")
print("Total words:", f"{total_words:,}")
print("Average chars/doc:", round(avg_chars, 2))
print("Average words/doc:", round(avg_words, 2))

Final corpus stats
------------------
Documents: 193009
Total characters: 583,626,806
Total words: 110,110,073
Average chars/doc: 3023.83
Average words/doc: 570.49

## approximate token estimation

In [16]:
token_est_3 = total_chars / 3
token_est_4 = total_chars / 4
token_est_5 = total_chars / 5

print("Approx token estimates")
print("----------------------")
print("At 3 chars/token :", f"{int(token_est_3):,}")
print("At 4 chars/token :", f"{int(token_est_4):,}")
print("At 5 chars/token :", f"{int(token_est_5):,}")

Approx token estimates
----------------------
At 3 chars/token : 194,542,268
At 4 chars/token : 145,906,701
At 5 chars/token : 116,725,361

## inspect clean sample

In [17]:
for i in range(5):
    print(f"\n--- Clean Sample {i+1} ---")
    print(filtered_df.iloc[i]["text"][:1000])

--- Clean Sample 1 ---
1891 ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਦੀ ਸੀਨੇਟ ਚੋਣਾਂ

ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਦੀ ਸੈਨੇਟ ਚੋਣਾਂ 20 ਅਤੇ 21 ਜਨਵਰੀ 1891 ਨੂੰ ਨਿਊਯਾਰਕ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੁਆਰਾ ਇੱਕ ਯੂ ਦੀ ਚੋਣ ਕਰਨ ਲਈ ਆਯੋਜਿਤ ਕੀਤੀਆਂ ਗਈਆਂ ਸਨ।ਐਸ. ਸੈਨੇਟਰ (ਕਲਾਸ 3), ਸੰਯੁਕਤ ਰਾਜ ਦੀ ਸੀਨੇਟ ਵਿੱਚ ਨਿਊਯਾਰਕ ਰਾਜ ਦੀ ਨੁਮਾਇੰਦਗੀ ਕਰਨ ਲਈ।
ਪਿਛੋਕਡ਼.
ਰਿਪਬਲਿਕਨ ਵਿਲੀਅਮ ਐਮ. ਈਵਾਰਟਸ 1885 ਵਿੱਚ ਇਸ ਸੀਟ ਲਈ ਚੁਣੇ ਗਏ ਸਨ ਅਤੇ ਉਨ੍ਹਾਂ ਦਾ ਕਾਰਜਕਾਲ 3 ਮਾਰਚ 1891 ਨੂੰ ਖਤਮ ਹੋ ਰਿਹਾ ਸੀ।
ਨਵੰਬਰ 1889 ਵਿੱਚ ਰਾਜ ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ, ਰਾਜ ਦੀ ਸੀਨੇਟ ਵਿੱਚ 19 ਗਣਤੰਤਰ ਅਤੇ 13 ਲੋਕਤੰਤਰੀ ਦੋ ਸਾਲ ਦੇ ਕਾਰਜਕਾਲ (1890-1891) ਲਈ ਚੁਣੇ ਗਏ ਸਨ। ਨਵੰਬਰ 1890 ਵਿੱਚ ਰਾਜ ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ, 68 ਡੈਮੋਕਰੇਟਸ ਅਤੇ 60 ਰਿਪਬਲਿਕਨ 1891 ਦੇ ਸੈਸ਼ਨ ਲਈ ਵਿਧਾਨ ਸਭਾ ਲਈ ਚੁਣੇ ਗਏ ਸਨ। 114ਵੀਂ ਨਿਊਯਾਰਕ ਰਾਜ ਵਿਧਾਨ ਸਭਾ ਦੀ ਮੀਟਿੰਗ 6 ਜਨਵਰੀ ਤੋਂ 30 ਅਪ੍ਰੈਲ 1891 ਤੱਕ ਅਲਬਾਨੀ, ਨਿਊਯਾਰਕ ਵਿਖੇ ਹੋਈ।
ਉਮੀਦਵਾਰ।
ਸਮਿਥ ਮਿਡ ਵੀਡ 1890 ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ ਵਿਧਾਨ ਸਭਾ ਦੇ ਨਿਯੰਤਰਣ ਦਾ ਦਾਅਵਾ ਕਰਨ ਦੇ ਜਮਹੂਰੀ ਯਤਨ ਦਾ ਇੱਕ ਪ੍ਰਮੁੱਖ ਪ੍ਰਬੰਧਕ ਅਤੇ ਵਿੱਤੀ ਸਮਰਥਕ ਸੀ। ਸੀਨੇਟ ਵਿੱਚ ਇੱਕ ਛੋਟੀ ਜਿਹੀ ਘੱਟ ਗਿਣਤੀ ਪਰ ਵਿਧਾਨ ਸਭਾ ਵਿੱਚ ਥੋਡ਼੍ਹੀ ਵੱਡੀ ਬਹੁਮਤ ਦੇ ਨਾਲ, ਲੋਕਤੰਤਰੀ ਵਿਧਾਨ ਸਭਾ ਦੇ ਸਾਂਝੇ ਬੈਲਟ ਉੱਤੇ ਆਪਣੇ ਆਪ ਵਿੱਚੋਂ ਇੱਕ ਨੂੰ ਚੁਣਨ ਲਈ ਸਥਿਤੀ ਵਿੱਚ ਸਨ। ਜੰਗਲ

--- Clean Sample 2 ---
ਫਲੇਵੋਨੋਲ-3-ਓ-ਟ੍ਰਿਗਲੂਕੋਸਾਈਡ ਓ-ਕੌਮਾਰੋਲ ਟ੍ਰਾਂਸਫਰੇਸ

ਇਨਜ਼ਾਈਮੋਲੋਜੀ ਵਿੱਚ, ਇੱਕ ਫਲੇਵੋਨੋਲ-3-ਓ-ਟ੍ਰਿਗਲੂਕੋਸਾਈਡ ਓ-ਕੌਮਾਰੋਲਟ੍ਰਾਂਸਫਰੇਸ () ਇੱਕ ਐਨਜ਼ਾਈਮ ਹੈ ਜੋ ਰਸਾਇਣਕ ਪ੍ਰਤੀਕ੍ਰਿਆ ਨੂੰ ਉਤਪ੍ਰੇਰਿਤ ਕਰਦਾ ਹੈ।
ਇਸ ਐਂਜ਼ਾਈਮ ਦੇ 3 ਘਟਾਓਣਾ 4-ਕੌਮਰੌਇਲ-ਕੋਆ, ਫਲੇਵੋਨੋਲ, ਅਤੇ 3-ਓ-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਾਈਡ ਹਨ, ਜਦੋਂ ਕਿ ਇਸ ਦੇ 4 ਉਤਪਾਦ ਕੋਆ, ਫਲੇਵੋਨੋਲ, 3-ਓ-[6-(4-ਕੌਮਰੌਇਲ)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-, ਅਤੇ ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਾਈਡ ਹਨ।
ਇਹ ਐਂਜ਼ਾਈਮ ਟ੍ਰਾਂਸਫਰਜ਼ ਦੇ ਪਰਿਵਾਰ ਨਾਲ ਸਬੰਧਤ ਹੈ, ਖਾਸ ਤੌਰ 'ਤੇ ਉਹ ਐਸਾਈਲਟ੍ਰਾਂਸਫਰੇਸ ਜੋ ਅਮੀਨੋਸਿਲ ਸਮੂਹਾਂ ਤੋਂ ਇਲਾਵਾ ਸਮੂਹਾਂ ਨੂੰ ਤਬਦੀਲ ਕਰਦੇ ਹਨ। ਇਸ ਐਂਜ਼ਾਈਮ ਕਲਾਸ ਦਾ ਯੋਜਨਾਬੱਧ ਨਾਮ 4-ਕੌਮਰੌਇਲ-ਕੋਆ ਹੈਃ ਫਲੇਵੋਨੋਲ-3-ਓ-[ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਲ-(1-> 2)-ਬੀਟਾ-ਡੀ-ਗਲੂਕੋਸਿਡ ਈ] 6-ਓ-4-ਕੌਮਰੌਇਲ ਟ੍ਰਾਂਸਫਰੇਸ ਹੈ।

--- Clean Sample 3 ---
ਪ੍ਰਸੰਨਾ ਪੇਓ

ਏਅਰ ਵਾਈਸ-ਮਾਰਸ਼ਲ ਐੱਮ. ਡੀ. ਏ. ਪ੍ਰਸੰਨਾ ਪਾਯੋ (ਜਿਸ ਨੂੰ ਏਵੀਐਮ ਪ੍ਰਸੰਤਾ ਪਾਯੋ ਵੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ) ਸ਼੍ਰੀਲੰਕਾ ਹਵਾਈ ਸੈਨਾ ਦਾ ਇੱਕ ਸੇਵਾਮੁਕਤ ਹਵਾਈ ਅਧਿਕਾਰੀ ਹੈ ਜਿਸ ਨੇ ਸ਼੍ਰੀਲੰਕਾ ਹਵਾਈ ਸੈਨਾ ਦੇ ਚੀਫ਼ ਆਫ਼ ਸਟਾਫ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਈ। ਇਸ ਨਿਯੁਕਤੀ ਤੋਂ ਪਹਿਲਾਂ, ਉਨ੍ਹਾਂ ਨੇ ਡਾਇਰੈਕਟਰ ਸਿਖਲਾਈ ਅਤੇ ਡਾਇਰੈਕਟਰ ਹਵਾਈ ਸੰਚਾਲਨ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਈ। ਉਨ੍ਹਾਂ ਨੇ ਸ਼੍ਰੀਲੰਕਾ ਦੇ ਸਭ ਤੋਂ ਵੱਡੇ ਹਵਾਈ ਸੈਨਾ ਅੱਡੇ, ਕਤੁਨਾਇਕੇ ਦੇ ਬੇਸ ਕਮਾਂਡਰ ਵਜੋਂ ਵੀ ਸੇਵਾ ਨਿਭਾਈ।
ਮੁਢਲਾ ਜੀਵਨ ਅਤੇ ਸਿੱਖਿਆ।
ਪੇਓ ਨੇ ਆਪਣੀ ਪਡ਼੍ਹਾਈ ਐਸ. ਏ. ਵਿੱਚ ਪੂਰੀ ਕੀਤੀ। ਥਾਮਸ ਕਾਲਜ, ਬੰਦਾਰਾਵੇਲਾ। ਫਿਰ ਉਹ 1985 ਵਿੱਚ ਜਨਰਲ ਡਿਊਟੀਜ਼ ਪਾਇਲਟ ਸ਼ਾਖਾ ਵਿੱਚ ਸ਼੍ਰੀਲੰਕਾਈ ਹਵਾਈ ਸੈਨਾ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਏ। ਉਹ ਰੱਖਿਆ ਸੇਵਾਵਾਂ ਕਮਾਂਡ ਅਤੇ ਸਟਾਫ ਕਾਲਜ ਸਪੁਗਾਸਕਾਂਡਾ, ਸ਼੍ਰੀਲੰਕਾ ਤੋਂ ਗ੍ਰੈਜੂਏਟ ਹੈ ਅਤੇ ਰਾਸ਼ਟਰੀ ਰੱਖਿਆ ਯੂਨੀਵਰਸਿਟੀ, ਪਾਕਿਸਤਾਨ ਤੋਂ ਐੱਨ. ਡੀ. ਸੀ. ਪੂਰੀ ਕੀਤੀ ਹੈ।
ਹਵਾਈ ਸੈਨਾ ਕੈਰੀਅਰ.
ਉਨ੍ਹਾਂ ਨੇ ਰੂਸ ਫੈਡਰੇਸ਼ਨ ਵਿੱਚ ਰੱਖਿਆ ਅਟੈਚੀ ਵਜੋਂ ਵੀ ਕੰਮ ਕੀਤਾ। ਏ. ਵੀ. ਐੱਮ. ਵਜੋਂ ਤਰੱਕੀ ਮਿਲਣ ਤੋਂ ਬਾਅਦ ਉਹ ਰੱਖਿਆ ਖੋਜ ਕੇਂਦਰ ਦੇ ਡਾਇਰੈਕਟਰ ਜਨਰਲ ਬਣੇ। ਉਹ 12 ਸਤੰਬਰ, 2022 ਨੂੰ ਸਲੈਫ ਦੇ ਚੀਫ਼ ਆਫ਼ ਸਟਾਫ ਵਜੋਂ ਸੇਵਾ ਨਿਭਾਉਂਦੇ ਹੋਏ ਸਰਗਰਮ ਸੇਵਾ ਤੋਂ ਸੇਵਾਮੁਕਤ ਹੋਏ।

--- Clean Sample 4 ---
ਤੰਗਖੁਲ ਲੋਕ

ਤੰਗਖੁਲ ਲੋਕ, ਜਿਨ੍ਹਾਂ ਨੂੰ ਤੰਗਖੁਲ ਨਾਗਾ ਵੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ, ਇੱਕ ਤਿੱਬਤੀ-ਬਰਮੀ ਨਸਲੀ ਸਮੂਹ ਹੈ ਜੋ ਭਾਰਤ-ਮਾਇਆਂਮਾਰ ਸਰਹੱਦੀ ਖੇਤਰ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ, ਜੋ ਉਖਰੂਲ ਜ਼ਿਲ੍ਹੇ ਅਤੇ ਉੱਤਰ-ਪੂਰਬੀ ਭਾਰਤੀ ਰਾਜ ਮਣੀਪੁਰ ਦੇ ਕਾਮਜੋਂਗ ਜ਼ਿਲ੍ਹੇ ਅਤੇ ਗੁਆਂਢੀ ਮਾਇਆਂਮਾਰ ਦੇ ਕੁਝ ਹਿੱਸਿਆਂ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ। ਇਸ ਅੰਤਰਰਾਸ਼ਟਰੀ ਸਰਹੱਦ ਦੇ ਬਾਵਜੂਦ, ਬਹੁਤ ਸਾਰੇ ਤੰਗਖੁਲ ਨੇ ਆਪਣੇ ਆਪ ਨੂੰ "ਇੱਕ ਰਾਸ਼ਟਰ" ਮੰਨਿਆ ਹੈ। ਤੰਗਖੁਲ" ਨਾਮ ਮੇਈਤੇਈ ਭਾਸ਼ਾ ਦੇ ਸ਼ਬਦਾਂ "ਤੰਗ" () ਤੋਂ ਉਤਪੰਨ ਹੋਇਆ ਹੈ, ਜਿਸਦਾ ਅਰਥ ਹੈ ਕ੍ਰਮਵਾਰ "ਦੁਰਲੱਭ" ਅਤੇ "ਖੁਲ" () ਦਾ ਅਰਥ ਹੈ "ਪਿੰਡ"। ਮੂਲ ਦੇ ਇੱਕ ਹੋਰ ਸਿਧਾਂਤ ਦੇ ਅਨੁਸਾਰ, "ਤੰਗਖੁਲ" ਸ਼ਬਦ "ਤੰਖੁਲ" ਤੋਂ ਲਿਆ ਗਿਆ ਹੈ, ਜਿਸਦਾ ਅਰਥ ਹੈ ਮੈਤੇਈ ਭਾਸ਼ਾ ਵਿੱਚ "ਪਿੰਡ ਤੋਂ ਵੱਧ"।
ਮਾਈਟੀਜ਼ ਨਾਲ ਸਬੰਧ।
ਦੁਖਦਾਈ ਪਿਆਰ ਅਤੇ ਅਲੱਗ ਹੋਣ ਦੀ ਮੇਇਤੇਈ ਦੇਵੀ, ਹਾਓਰੇਮਾ, ਅਸਲ ਵਿੱਚ ਤੰਗਖੁਲ ਮੂਲ ਦਾ ਇੱਕ ਦੇਵਤਾ ਸੀ। ਉਹ ਚਿੰਗਡਾਈ ਪਿੰਡ ਦੇ ਇੱਕ ਤੰਗਖੁਲ ਮੁਖੀਆ "ਖੇਲੇਮਬਾ" ਦੀ ਧੀ ਸੀ ਅਤੇ ਚਿੰਗਸ਼ੋਂਗ ਪਿੰਡ ਦੇ ਇੱਕ ਤੰਗਖੁਲ ਮੁਖੀਆ "ਖਮਲੰਗਬਾ" ਨਾਲ ਵਿਆਹੀ ਹੋਈ ਸੀ। ਖਮਲੰਗਬਾ ਨਾਲ ਵਿਆਹ ਕਰਨ ਦੇ ਬਾਵਜੂਦ, ਉਸ ਦਾ ਮੇਈਤੇਈ ਰਾਜਾ "ਮੇਇਡਿੰਗੂ ਤਬੰਗਬਾ" ਨਾਲ ਗੁਪਤ ਪ੍ਰੇਮ ਸਬੰਧ ਸੀ, ਜਿਸ ਨੂੰ "ਤਬੰਗ ਸਫਬਾ" (1359-1394) ਵੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ। ਦੋਵਾਂ ਦੇ ਵਿਚਕਾਰ ਗੁਪਤ ਸਬੰਧਾਂ ਦਾ ਪਤਾ ਲੱਗਣ 'ਤੇ,

--- Clean Sample 5 ---
ਸਾਈਨਾਸ (ਕ੍ਰੇਟਰ)

ਸਾਇਨਾਸ ਇੱਕ ਛੋਟਾ ਚੰਦਰ ਪ੍ਰਭਾਵ ਖੱਡਾ ਹੈ ਜੋ ਚੰਦਰਮਾ ਦੇ ਪੂਰਬੀ ਹਿੱਸੇ ਵਿੱਚ ਘੋਡ਼ੇ ਦੇ ਟਰੈਂਕੁਲੀਟੈਟਿਸ ਉੱਤੇ ਸਥਿਤ ਹੈ। ਇਸ ਦਾ ਵਿਆਸ 12 ਕਿਲੋਮੀਟਰ ਹੈ। ਇਸ ਦਾ ਨਾਮ ਯੂਨਾਨੀ ਮੈਗਨੇਟ ਸਾਇਮਨ ਸਿਨਾਜ਼ ਦੇ ਨਾਮ ਉੱਤੇ ਰੱਖਿਆ ਗਿਆ ਸੀ। ਇਹ ਇੱਕ ਅਲੱਗ-ਥਲੱਗ ਗਠਨ ਹੈ ਜੋ ਚੰਦਰਮਾ ਘੋਡ਼ੇ ਦੇ ਮੱਧ ਬਿੰਦੂ ਦੇ ਬਹੁਤ ਨੇਡ਼ੇ ਸਥਿਤ ਹੈ। ਸਾਈਨਾ ਗੋਲ ਅਤੇ ਕਟੋਰੇ ਦੇ ਆਕਾਰ ਦਾ ਹੁੰਦਾ ਹੈ, ਜਿਸ ਦੇ ਵਿਚਕਾਰਲੇ ਬਿੰਦੂ 'ਤੇ ਇੱਕ ਛੋਟੀ ਜਿਹੀ ਮੰਜ਼ਲ ਹੁੰਦੀ ਹੈ। ਇੱਕ ਸੁੰਗਡ਼ਨ ਵਾਲੀ ਰਿੱਜ ਕ੍ਰੇਟਰ ਦੇ ਪੂਰਬੀ ਕਿਨਾਰੇ ਨੂੰ ਕੱਟਦੀ ਹੈ, ਅਤੇ ਕਈ ਚੰਦਰਮਾ ਦੇ ਗੁੰਬਦ ਉੱਤਰ ਵਿੱਚ ਸਥਿਤ ਹਨ।
ਨੇਡ਼ਲੇ ਗੱਡਿਆਂ ਵਿੱਚ ਉੱਤਰ-ਪੱਛਮ ਵਿੱਚ ਜਾਨਸੇਨ ਅਤੇ ਕੈਰਲ, ਦੱਖਣ-ਪੂਰਬ ਵਿੱਚ ਆਰਿਆਭਟ ਅਤੇ ਦੱਖਣ ਵਿੱਚ ਮਾਸਕੇਲਿਨ ਸ਼ਾਮਲ ਹਨ।
ਸੈਟੇਲਾਈਟ ਗਰੱਭਸਥਾਨਾਂ।
ਪਰੰਪਰਾ ਦੁਆਰਾ ਇਨ੍ਹਾਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਦੀ ਪਛਾਣ ਚੰਦਰ ਨਕਸ਼ਿਆਂ ਉੱਤੇ ਕ੍ਰੈਟਰ ਦੇ ਮੱਧ ਬਿੰਦੂ ਦੇ ਪਾਸੇ ਪੱਤਰ ਰੱਖ ਕੇ ਕੀਤੀ ਜਾਂਦੀ ਹੈ ਜੋ ਕਿ ਸਿਨਾ ਦੇ ਸਭ ਤੋਂ ਨੇਡ਼ੇ ਹੈ।

## save clean corpus as parquet

In [18]:
cleaned_parquet_path = data_dir / "punjabi_corpus_cleaned.parquet"
filtered_df.to_parquet(cleaned_parquet_path, index=False)

print("Saved cleaned parquet to:", cleaned_parquet_path)

Saved cleaned parquet to: /Users/gurpejsingh/Desktop/gpt2-finetune-mac/training-punjabi-gpt/data/punjabi_corpus_cleaned.parquet

## save pretraining text JSONL

In [19]:
cleaned_jsonl_path = data_dir / "punjabi_corpus_cleaned.jsonl"

with open(cleaned_jsonl_path, "w", encoding="utf-8") as f:
    for text in filtered_df["text"]:
        f.write(json.dumps({"text": text}, ensure_ascii=False) + "\n")

print("Saved cleaned JSONL to:", cleaned_jsonl_path)

Saved cleaned JSONL to: /Users/gurpejsingh/Desktop/gpt2-finetune-mac/training-punjabi-gpt/data/punjabi_corpus_cleaned.jsonl

## save plain text corpus too

In [20]:
plain_text_path = data_dir / "punjabi_corpus_cleaned.txt"

with open(plain_text_path, "w", encoding="utf-8") as f:
    for text in filtered_df["text"]:
        f.write(text.replace("\n", " ").strip() + "\n")

print("Saved plain text corpus to:", plain_text_path)

Saved plain text corpus to: /Users/gurpejsingh/Desktop/gpt2-finetune-mac/training-punjabi-gpt/data/punjabi_corpus_cleaned.txt

## save summary report

In [21]:
summary = {
    "original_rows": int(len(corpus_df)),
    "filtered_rows": int(len(filtered_df)),
    "removed_rows": int(len(corpus_df) - len(filtered_df)),
    "total_characters": int(total_chars),
    "total_words": int(total_words),
    "avg_chars_per_doc": float(avg_chars),
    "avg_words_per_doc": float(avg_words),
    "approx_tokens_3_chars_per_token": int(token_est_3),
    "approx_tokens_4_chars_per_token": int(token_est_4),
    "approx_tokens_5_chars_per_token": int(token_est_5),
}

summary_path = outputs_dir / "corpus_summary.json"

with open(summary_path, "w", encoding="utf-8") as f:
    json.dump(summary, f, ensure_ascii=False, indent=2)

print("Saved summary to:", summary_path)
print(summary)

Saved summary to: /Users/gurpejsingh/Desktop/gpt2-finetune-mac/training-punjabi-gpt/outputs/corpus_summary.json
{'original_rows': 200000, 'filtered_rows': 193009, 'removed_rows': 6991, 'total_characters': 583626806, 'total_words': 110110073, 'avg_chars_per_doc': 3023.832080369309, 'avg_words_per_doc': 570.4919097036926, 'approx_tokens_3_chars_per_token': 194542268, 'approx_tokens_4_chars_per_token': 145906701, 'approx_tokens_5_chars_per_token': 116725361}